# https://github.com/ViacheslavGbc/assignment

language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - pwd
  - mkdir dist
  - cd dist
  - ls -la 

install:
  - ls -la
  # install all the dependencies you need here
  - npm install
  - ls -la
